nationalities = [
    "Afghan", "Albanian", "Algerian", "Andorran", "Angolan", "Antiguan", "Argentine",
    "Armenian", "Australian", "Austrian", "Azerbaijani", "Bahamian", "Bahraini",
    "Bangladeshi", "Barbadian", "Belarusian", "Belgian", "Belizean", "Beninese",
    "Bhutanese", "Bolivian", "Bosnian", "Botswanan", "Brazilian", "Bruneian",
    "Bulgarian", "Burkinabe", "Burundian", "Cabo Verdean", "Cambodian", "Cameroonian",
    "Canadian", "Central African", "Chadian", "Chilean", "Chinese", "Colombian",
    "Comorian", "Congolese", "Costa Rican", "Croatian", "Cuban", "Cypriot",
    "Czech", "Danish", "Djiboutian", "Dominican", "Dutch", "East Timorese",
    "Ecuadorean", "Egyptian", "Salvadoran", "Equatorial Guinean", "Eritrean",
    "Estonian", "Eswatini", "Ethiopian", "Fijian", "Finnish", "French",
    "Gabonese", "Gambian", "Georgian", "German", "Ghanaian", "Greek",
    "Grenadian", "Guatemalan", "Guinean", "Guyanese", "Haitian", "Honduran",
    "Hungarian", "Icelandic", "Indian", "Indonesian", "Iranian", "Iraqi",
    "Irish", "Israeli", "Italian", "Ivorian", "Jamaican", "Japanese",
    "Jordanian", "Kazakhstani", "Kenyan", "Kiribati", "Kuwaiti", "Kyrgyz",
    "Laotian", "Latvian", "Lebanese", "Lesotho", "Liberian", "Libyan",
    "Liechtensteiner", "Lithuanian", "Luxembourger", "Macedonian", "Malagasy",
    "Malawian", "Malaysian", "Maldivian", "Malian", "Maltese", "Marshallese",
    "Mauritanian", "Mauritian", "Mexican", "Micronesian", "Moldovan", "Monacan",
    "Mongolian", "Montenegrin", "Moroccan", "Mozambican", "Namibian", "Nauruan",
    "Nepalese", "Dutch", "New Zealander", "Nicaraguan", "Nigerien", "Nigerian",
    "North Korean", "Norwegian", "Omani", "Pakistani", "Palauan", "Palestinian",
    "Panamanian", "Papua New Guinean", "Paraguayan", "Peruvian", "Philippine",
    "Polish", "Portuguese", "Qatari", "Romanian", "Russian", "Rwandan",
    "Saint Kitts and Nevis", "Saint Lucian", "Saint Vincentian", "Samoan",
    "San Marinese", "Sao Tomean", "Saudi", "Scottish", "Senegalese", "Serbian",
    "Seychellois", "Sierra Leonean", "Singaporean", "Slovak", "Slovenian",
    "Solomon Islander", "Somali", "South African", "South Korean", "Spanish",
    "Sri Lankan", "Sudanese", "Surinamese", "Swedish", "Swiss", "Syrian",
    "Tajikistani", "Tanzanian", "Thai", "Togolese", "Tongan", "Trinidadian",
    "Tunisian", "Turkish", "Turkmen", "Tuvaluan", "Ugandan", "Ukrainian",
    "Emirati", "British", "American", "Uruguayan", "Uzbekistani", "Vanuatu",
    "Vatican", "Venezuelan", "Vietnamese", "Yemeni", "Zambian", "Zimbabwean"
]
